#!/bin/sh


function _gui-container {
  local _COMMANDS="create-container create-entry delete-entry create-home delete-home" 

  declare -A _PODMAN=(
    ["create-container"]="$(podman images --format '{{ .Repository}}:{{ .Tag }}')"
    ["create-entry"]="$(podman ps -a --format '{{ .Names }}')"
    ["delete-entry"]="$(podman ps -a --format '{{ .Names }}')"
    ["create-home"]="$(podman ps -a --format '{{ .Names }}')"
    ["delete-home"]="$(ls ~/.gui-container)"

  )

  COMPREPLY=()

  local current_w=${COMP_WORDS[COMP_CWORD]}
  
  if [ "$COMP_CWORD" -eq 1 ] ; then
    COMPREPLY=("$( compgen -W "${_COMMANDS}" -- "$current_w")")
  elif [ "$COMP_CWORD" -eq 2 ] ; then
    COMPREPLY=("$( compgen -W "${_PODMAN[${COMP_WORDS[1]}]}" -- "$current_w")")
  fi
}

complete -F _gui-container gui-container
